create sequence hibernate_sequence start 1 increment 1;

create table article_tags (
    article_id int8 not null,
    tags varchar(255)
);

create table articles (
    id int8 not null,
    date varchar(255),
    heading varchar(255),
    text varchar(10240),
    user_id int8,
    modification_id int8 not null,
    primary key (id)
);

create table bodies (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table body_type_names (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table body_types (
    id int8 generated by default as identity,
    description varchar(10240),
    photo varchar(255),
    years varchar(255),
    body_type_name_id int8,
    generation_id int8,
    restyle_name int8,
    primary key (id)
);

create table carmodels (
    id int8 not null,
    description varchar(10240),
    name varchar(255),
    manufacturer_id int8,
    primary key (id)
);

create table cars (
    id int8 generated by default as identity,
    description varchar(10240),
    photo varchar(255),
    years varchar(255),
    body_id int8,
    body_type_id int8,
    carmodel_id int8,
    drive_id int4,
    engine_id int8,
    generation_id int8,
    manufacturer_id int8,
    modification_id int8,
    restyle_id int8,
    title_id int8,
    primary key (id)
);

create table comments (
    id int8 generated by default as identity,
    text varchar(255),
    article_id int8,
    car_id int8,
    photo_id int8,
    user_id int8,
    primary key (id)
);

create table countries (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table drives (
    id int4 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table engines (
    id int8 generated by default as identity,
    description varchar(10240),
    name varchar(255),
    power varchar(255),
    torque varchar(255),
    volume varchar(255),
    engine_type_id int4,
    fuel_id int4,
    manufacturer_id int8,
    primary key (id)
);

create table engine_types (
    id int4 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table fuels (
    id int4 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table gear_boxes (
    id int8 generated by default as identity,
    description varchar(255),
    name varchar(255),
    type varchar(255),
    primary key (id)
);

create table gear_box_types (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table generations (
    id int8 not null,
    description varchar(10240),
    name varchar(255),
    photo varchar(255),
    years varchar(255),
    body_id int8,
    carmodel_id int8,
    manufacturer_id int8,
    title_id int8,
    primary key (id)
);

create table manufacturers (
    id int8 generated by default as identity,
    description varchar(10240),
    logo varchar(255),
    name varchar(255),
    country_id int8,
    primary key (id)
);

create table modifications (
    id int8 not null,
    description varchar(10240),
    name varchar(255),
    photo varchar(255),
    years varchar(255),
    body_id int8,
    body_type_id int8,
    drive_id int4,
    engine_id int8,
    gear_box_id int8,
    primary key (id)
);

create table persons (
    id int8 generated by default as identity,
    date_of_birth varchar(255),
    description varchar(10240),
    name varchar(255),
    photo varchar(255),
    points2021 int4,
    country_id int8,
    series_id int8,
    team_id int8,
    primary key (id)
);

create table photos (
    modification_id int8 not null,
    photos varchar(255)
);

create table photos1 (
    id int8 generated by default as identity,
    description varchar(255),
    name varchar(255),
    primary key (id)
);

create table photos2 (
    gear_box_id int8 not null,
    photos_id int8 not null
);

create table race_classes (
    id int8 generated by default as identity,
    name varchar(255),
    series_id int8,
    primary key (id)
);

create table race_results (
    id int8 generated by default as identity,
    bonus int4,
    gap varchar(255),
    out varchar(255),
    points int4,
    position int4,
    time varchar(255),
    modification_id int8,
    navigator_id int8,
    pilot_id int8,
    race_id int8,
    race_class_id int8,
    series_id int8,
    team_id int8,
    primary key (id)
);

create table races (
    id int8 generated by default as identity,
    finish_date varchar(255),
    name varchar(255),
    season varchar(255),
    stage_number int4,
    start_date varchar(255),
    country_id int8,
    series_id int8,
    track_id int8,
    primary key (id)
);

create table restyles (
    id int8 not null,
    name varchar(255),
    generation_id int8,
    primary key (id)
);

create table series (
    id int8 generated by default as identity,
    description varchar(10240),
    name varchar(255),
    photo varchar(255),
    primary key (id)
);

create table teams (
    id int8 generated by default as identity,
    description varchar(10240),
    logo varchar(255),
    name varchar(255),
    points2021 int4,
    year_of_foundation varchar(255),
    country_id int8,
    series_id int8,
    primary key (id)
);

create table titles (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table tracks (
    id int8 generated by default as identity,
    city varchar(255),
    description varchar(10240),
    name varchar(255),
    year_of_construction varchar(255),
    country_id int8,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table usr (
    id int8 not null,
    activation_code varchar(255),
    active boolean not null,
    avatar varchar(255),
    email varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);

alter table if exists photos2
    add constraint UK_d74k8vstt34s9ky79b8fdxe6i
    unique (photos_id);

alter table if exists article_tags
    add constraint FKeoil73g36agokjw6vuklqgli3
    foreign key (article_id) references articles;

alter table if exists articles
    add constraint FKnevmey86fpcevtgfq4v5a454o
    foreign key (user_id) references usr;

alter table if exists articles
    add constraint FKiljx590jmlmfn1xvgxbfwe472
    foreign key (modification_id) references modifications;

alter table if exists body_types
    add constraint FKkjqt0bx565srqgolo7w646nl4
    foreign key (body_type_name_id) references body_type_names;

alter table if exists body_types
    add constraint FKdbju35jmt7no05b8m7iu8jw7m
    foreign key (generation_id) references generations;

alter table if exists body_types
    add constraint FKaaj9l6kj4np5og164e7mwn3l
    foreign key (restyle_name) references restyles;

alter table if exists carmodels
    add constraint FKmd4py0fgauoe6qmlfuung7x0b
    foreign key (manufacturer_id) references manufacturers;

alter table if exists cars
    add constraint FKj5k3l1aieb5fk0ao804q2h7wo
    foreign key (body_id) references bodies;

alter table if exists cars
    add constraint FKeox9shjlnnh5u1fxoibrlbvod
    foreign key (body_type_id) references body_types;

alter table if exists cars
    add constraint FKocsj0m69y2iyggjki5g4r5t5x
    foreign key (carmodel_id) references carmodels;

alter table if exists cars
    add constraint FK1gysi3s9c6e2gjq6ch5s6ri4o
    foreign key (drive_id) references drives;

alter table if exists cars
    add constraint FKijdkhps4dwsv7r4jkfic2jaue
    foreign key (engine_id) references engines;

alter table if exists cars
    add constraint FKg1qo6b481ypqbwglkuxdw6cmf
    foreign key (generation_id) references generations;

alter table if exists cars
    add constraint FK6hctqxdwhcl223hfxh4swhdxm
    foreign key (manufacturer_id) references manufacturers;

alter table if exists cars
    add constraint FK5q6hnn4okstwmb88x3vcc8at4
    foreign key (modification_id) references modifications;

alter table if exists cars
    add constraint FKsi1axdma7fxnpi1vj91l0yhrm
    foreign key (restyle_id) references restyles;

alter table if exists cars
    add constraint FKfcwm0ohny5aq96i6wtmytgsht
    foreign key (title_id) references titles;

alter table if exists comments
    add constraint FKk4ib6syde10dalk7r7xdl0m5p
    foreign key (article_id) references articles;

alter table if exists comments
    add constraint FKci71iq73l6xmtv1k38w52dmq0
    foreign key (car_id) references cars;

alter table if exists comments
    add constraint FKqd6gv069buf0mcn1hqeumx9ui
    foreign key (photo_id) references photos1;

alter table if exists comments
    add constraint FKoe193dqy22vps4cq755krf76s
    foreign key (user_id) references usr;

alter table if exists engines
    add constraint FKnr78uyibpvli4spmse2xf19d1
    foreign key (engine_type_id) references engine_types;

alter table if exists engines
    add constraint FKtpvememrnlr0fg7sr4bvipfdx
    foreign key (fuel_id) references fuels;

alter table if exists engines
    add constraint FKt2fwfllvs9j9sfhk9lvpw6qmn
    foreign key (manufacturer_id) references manufacturers;

alter table if exists generations
    add constraint FK28ojfc1swpghn8idesrh0bei4
    foreign key (body_id) references bodies;

alter table if exists generations
    add constraint FKqqqiev9wet1abors4xoxgk8ar
    foreign key (carmodel_id) references carmodels;

alter table if exists generations
    add constraint FKfcp7bjiwk03racj33tufdx7sc
    foreign key (manufacturer_id) references manufacturers;

alter table if exists generations
    add constraint FK84qxm5hqv142dbey5w15e2nmg
    foreign key (title_id) references titles;

alter table if exists manufacturers
    add constraint FKe13erdojygfdwr7mvn3m6dtql
    foreign key (country_id) references countries;

alter table if exists modifications
    add constraint FKahpqbbqeqlmqd27al6x63ij3r
    foreign key (body_id) references bodies;

alter table if exists modifications
    add constraint FKkthx9rvm3nxn4v0lotm7ssbnm
    foreign key (body_type_id) references body_types;

alter table if exists modifications
    add constraint FKaawhkfos8aesmyjskq4bovr3o
    foreign key (drive_id) references drives;

alter table if exists modifications
    add constraint FKkjehb41wtypa20pwg5rhw9igi
    foreign key (engine_id) references engines;

alter table if exists modifications
    add constraint FKmo732jbmt8xabxm7qyj3oiwhd
    foreign key (gear_box_id) references gear_boxes;

alter table if exists persons
    add constraint FKerkc4hn581s5tffbfj3xlu864
    foreign key (country_id) references countries;

alter table if exists persons
    add constraint FKctpak1qw90frkk28qeyj06rfo
    foreign key (series_id) references series;

alter table if exists persons
    add constraint FK7uufq3sspwt2yv2wm3184ujcl
    foreign key (team_id) references teams;

alter table if exists photos
    add constraint FKkqc8g0j0os0wqh25jsh6mljwk
    foreign key (modification_id) references modifications;

alter table if exists photos2
    add constraint FKeebmorxvoumeco912btpf8pn
    foreign key (photos_id) references photos1;

alter table if exists photos2
    add constraint FKtmdknkas1ppbh73nwb0ibag87
    foreign key (gear_box_id) references gear_boxes;

alter table if exists race_classes
    add constraint FK3xopo1bv1cr84pd29pkndqwb6
    foreign key (series_id) references series;

alter table if exists race_results
    add constraint FKol0137qxc1jjpcnh1pxd3lwgp
    foreign key (modification_id) references modifications;

alter table if exists race_results
    add constraint FKa74tghpvgr8pkgrnf8t2ndar8
    foreign key (navigator_id) references persons;

alter table if exists race_results
    add constraint FKj9tca6majaptginrlua8nl83o
    foreign key (pilot_id) references persons;

alter table if exists race_results
    add constraint FK2elke3gjhe8xwitsftgj573cn
    foreign key (race_id) references races;

alter table if exists race_results
    add constraint FKgcw5qw464sdqso69b3oscaffj
    foreign key (race_class_id) references race_classes;

alter table if exists race_results
    add constraint FKppsywyqtq2ongtt7pwx3crf4s
    foreign key (series_id) references series;

alter table if exists race_results
    add constraint FKog6c3y9gos90b61bw11f5c0tb
    foreign key (team_id) references teams;

alter table if exists races
    add constraint FKciipprrd0p4v2ggtsesdt8kcd
    foreign key (country_id) references countries;

alter table if exists races
    add constraint FK202rvabgtbk6tp6k4840rku80
    foreign key (series_id) references series;

alter table if exists races
    add constraint FKo4mqpy8elrysd8iwonfkj0mgw
    foreign key (track_id) references tracks;

alter table if exists restyles
    add constraint FKt4x6pj06rjh86ve5suhqcer9e
    foreign key (generation_id) references generations;

alter table if exists teams
    add constraint FK7oxg99kw26u7w7swuu6tivxmr
    foreign key (country_id) references countries;

alter table if exists teams
    add constraint FK5wmcm3k4ffvv9659a21kjhlpr
    foreign key (series_id) references series;

alter table if exists tracks
    add constraint FKabuh10nuih76bprq74wlrlv7
    foreign key (country_id) references countries;

alter table if exists user_role
add constraint FKfpm8swft53ulq2hl11yplpr5
foreign key (user_id) references usr;